plugins {
    id 'com.github.johnrengelman.shadow' version '7.1.2' // Плагин для тенизации JAR-файла
    id 'org.jetbrains.kotlin.jvm' version '2.1.0' // Плагин для Kotlin
}

group = 'net.Mirik9724'
version = '0.8-b26'

repositories {
    mavenCentral()
    maven {
        name = "spigotmc-repo"
        url = "https://hub.spigotmc.org/nexus/content/repositories/snapshots/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
    maven { url = uri("https://repo1.maven.org/maven2/") }
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    maven {
        url 'https://repo.papermc.io/repository/maven-releases/'
    }
    maven { url = uri("https://repo.papermc.io/repository/maven-snapshots")}
    maven { url 'https://jitpack.io' }
}

dependencies {
    compileOnly("org.spigotmc:spigot-api:1.18.2-R0.1-SNAPSHOT")
    compileOnly 'net.md-5:bungeecord-api:1.19-R0.1-SNAPSHOT'
    compileOnly("com.velocitypowered:velocity-api:3.4.0-SNAPSHOT")

    // https://mvnrepository.com/artifact/org.bstats/bstats-base
//    implementation("org.bstats:bstats-base:3.0.2")

    // Для работы с Kotlin
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"

    // Adventure API (Core + MiniMessage)
    implementation 'net.kyori:adventure-api:4.14.0'
    implementation 'net.kyori:adventure-platform-bukkit:4.3.0'
    implementation 'net.kyori:adventure-text-serializer-legacy:4.14.0'
    implementation 'net.kyori:adventure-text-serializer-gson:4.14.0'
    implementation 'net.kyori:adventure-text-minimessage:4.14.0'

    // Зависимости для работы с Jackson (для работы с JSON)
    implementation 'com.fasterxml.jackson.core:jackson-core:2.14.1'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.14.1'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.14.1'

//    implementation("org.yaml:snakeyaml:2.2") // или актуальную версию

    implementation files('libs/MirikAPI-0.1.4.2.jar')
}

def targetJavaVersion = 17
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}

// Настройка теневого JAR-файла для включения зависимостей
shadowJar {
    archiveClassifier.set('') // Убираем "shadow" в названии JAR-файла
//    relocate("org.bstats", "net.Mirik9724.whitelist_ultra.bstats") // важно для защиты от конфликтов
}

// Убедитесь, что билд включает сборку теневого JAR
tasks.build {
    dependsOn shadowJar
}

sourceSets {
    main {
        kotlin {
            exclude("net/Mirik9724/whitelist_ultra/Bu")
        }
    }
}
