# Global placeholders
# @nick - player`s nickname(you cann`t use it everywhere)
#
# Here you can add your placeholders
placeholders:
  "@fu": "Fu!!!"
  "@custom": "CustomValue"
  "@test": "Test!"

error:
  file_: "The test messenge"
  file_does_not-exist: "File does not exist."
  underknewcom: "Unknown command: @undsubcom"
  subc: "Please specify the subcommand."
commands:
  subc: "Please write a subcommand"
  usage: "Usage: " # +usage for command
  change:
    old_not_found: "The old nickname was not found in the list."
    duplicate: "The new nickname already exists in the list."
    success: "Nickname changed successfully."

  remove:
    m1: "Player @nick was removed from the whitelist."
    m2: "Player @nick is not found in the whitelist."
    kick: "You have been removed from the whitelist"

  add:
    m1: "Player @nick successfully added to whitelist."
    m2: "Player @nick already on the whitelist."

  check:
    found: "Player @nick is in the whitelist."
    not_found: " Player @nick is not in the whitelist."

  list: "Whitelist: " # + list of player in WLU
  player: "Player @nick"
reload: "The plugin has been successfully reloaded!"
kick: |
  You are not on the whitelist
  Join to us in Discord!

version:
  v_no_connect: "New plugin versions failed."
  v_no_found: "Update not found."
  v_found: "Update found here is the latest version: @new_v"

# Use BStats metrics (Please do not disable it so that I have an idea about the plugin users (anonymous info))
use-metric: "True"
check_updates: "True"