name: whitelist_ultra
version: "${version}"
main: net.Mirik9724.whitelist_ultra.Bukkit.WLUBu
api-version: '1.18'
description: Whitelist works with nicknames without uuid and case sensitive.
depend: [MirikAPI]
commands:
  whitelist-ultra:
    aliases:
      - wlu
    usage: /wlu <reload|list|check|change|del|add>
    permission: whitelist-ultra.admin
    permission-messange: You don not have permission for this command
    subcommands:
      add:
        description: Add player to WL
        permission: whitelist-ultra.add
        permission-messange: You don not have permission for this command
      remove:
        description: Remove player to WL
        permission: whitelist-ultra.remove
        permission-messange: You don not have permission for this command
        aliases:
          - del
      list:
        description: Show WL
        permission: whitelist-ultra.list
        permission-messange: You don not have permission for this command
      reload:
        description: Reload plugin
        permission: whitelist-ultra.reload
        permission-messange: You don not have permission for this command
      check:
        description: Reload plugin
        permission: whitelist-ultra.check
        permission-messange: You don not have permission for this command
      change:
        description: Reload plugin
        permission: whitelist-ultra.check
        permission-messange: You don not have permission for this command

folia-supported: true
