# En - Ici, vous pouvez télécharger des traductions prêtes à l'emploi of the config into your language (if it is translated)
# Ru - Здесь вы можете скачать готовые переводы конфига на ваш язык(если он переведён)
# Ua - Тут ви можете завантажити готові переклади конфігу на вашу мову (якщо вона перекладена)
# Ch(Simple) - 您可以在此处下载现成的配置翻译版本（如果已翻译）
# Fr - Ici, vous pouvez télécharger des traductions prêtes à l'emploi de la configuration dans votre langue (si elle est traduite)
# La - Hic potes download praeparata configurationis translationes in linguam tuam(si translatum est)
# De - Hier können Sie fertige Übersetzungen der Konfiguration in Ihre Sprache(falls verfügbar)
# https://github.com/Mirik9724/whitelist-ultra/blob/main/lang

# Espaces réservés globaux
# @nick - surnom du joueur (ne peut pas être utilisé partout)
#
# Vous pouvez ajouter vos propres espaces réservés ici
placeholders:
  "@fu": "Fu !!!"
  "@custom": "Valeur personnalisée"
  "@test": "Test !"

check_updates: "True"

error:
  file_: "Message de test"
  file_does_not-exist: "Le fichier n'existe pas."
  underknewcom: "Commande inconnue : @undsubcom"
  subc: "Veuillez préciser une sous-commande."

commands:
  subc: "Veuillez saisir une sous-commande"
  usage: "Utilisation : " # + utilisation de la commande

  change:
    old_not_found: "L'ancien pseudo est introuvable dans la liste."
    duplicate: "Le nouveau pseudo existe déjà dans la liste."
    success: "Le pseudo a été modifié avec succès."

  remove:
    m1: "Le joueur @nick a été retiré de la liste blanche."
    m2: "Le joueur @nick n'est pas dans la liste blanche."
    kick: "Vous avez été retiré de la liste blanche."

  add:
    m1: "Le joueur @nick a été ajouté à la liste blanche avec succès."
    m2: "Le joueur @nick est déjà dans la liste blanche."

  check:
    found: "Le joueur @nick est dans la liste blanche."
    not_found: "Le joueur @nick n'est pas dans la liste blanche."

  list: "Liste blanche : " # + liste des joueurs dans WLU
  player: "Joueur @nick"

reload: "Le plugin a été rechargé avec succès !"
kick: "Vous n'êtes pas sur la liste blanche."

version:
  v_no_connect: "Impossible de récupérer la nouvelle version du plugin."
  v_no_found: "Aucune mise à jour trouvée."
  v_found: "Mise à jour trouvée. Dernière version : @new_v"

# Utiliser les métriques BStats
# (Veuillez ne pas les désactiver afin que je puisse avoir une idée de l'utilisation du plugin — données anonymes)
use-metric: True

# Pour le développeur (me) :
debag: False # ne fonctionne pas pour le moment
# import net.Mirik9724.whitelist_ultra.Sp.WLU.nick
# WLU.nick
#
# plugin.logger.warning("")
# plugin.logger.info("")
# plugin.logger.fatal("")
# WLU.instance.logger.info("")
#
# println - SUPPRIMER