# En - Hier können Sie fertige Übersetzungen herunterladen of the config into your language (if it is translated)
# Ru - Здесь вы можете скачать готовые переводы конфига на ваш язык(если он переведён)
# Ua - Тут ви можете завантажити готові переклади конфігу на вашу мову (якщо вона перекладена)
# Ch(Simple) - 您可以在此处下载现成的配置翻译版本（如果已翻译）
# Fr - Ici, vous pouvez télécharger des traductions prêtes à l'emploi de la configuration dans votre langue (si elle est traduite)
# La - Hic potes download praeparata configurationis translationes in linguam tuam(si translatum est)
# De - Hier können Sie fertige Übersetzungen der Konfiguration in Ihre Sprache(falls verfügbar)
# https://github.com/Mirik9724/whitelist-ultra/blob/main/lang

# Globale Platzhalter
# @nick - Spielername(you cann`t use it everywhere)
#
# Hier können Sie Ihre eigenen Platzhalter hinzufügen
placeholders:
  "@fu": "Fu!!!"
  "@custom": "CustomValue"
  "@test": "Test!"

error:
  file_: "Testnachricht"
  file_does_not-exist: "Datei existiert nicht."
  underknewcom: "Unbekannter Befehl: @undsubcom"
  subc: "Bitte geben Sie den Unterbefehl an."
commands:
  usage: "Verwendung: " # +usage for command
  change:
    old_not_found: "Der alte Spitzname wurde in der Liste nicht gefunden."
    duplicate: "Der neue Spitzname ist bereits in der Liste vorhanden."
    success: "Spitzname erfolgreich geändert."

  remove:
    m1: "Spieler @nick wurde von der Whitelist entfernt."
    m2: "Spieler @nick ist nicht in der Whitelist."
    kick: "Sie wurden von der Whitelist entfernt"

  add:
    m1: "Spieler @nick wurde erfolgreich zur Whitelist hinzugefügt."
    m2: "Spieler @nick ist bereits auf der Whitelist."

  check:
    found: "Spieler @nick ist auf der Whitelist."
    not_found: " Spieler @nick ist nicht auf der Whitelist."

  list: "Whitelist: " # + list of player in WLU
  player: "Spieler @nick"
reload: "Das Plugin wurde erfolgreich neu geladen!"
kick: "Sie stehen nicht auf der Whitelist."

version:
  v_no_connect: "Neue Plugin-Versionen fehlgeschlagen."
  v_no_found: "Update nicht gefunden."
  v_found: "Update gefunden, hier ist die neueste Version: @new_v"

# Use BStats metrics (Please do not disable it so that I have an idea about the plugin users (anonymous info))
use-metric: True

# For dev(me):
debag: False #Now it no work
# import net.Mirik9724.whitelist_ultra.Sp.WLU.nick
# WLU.nick
#
# plugin.logger.warning(")
# plugin.logger.info("")
# plugin.logger.fatal("")
# WLU.instance.logger.info("")
#
# println - DELITE