# En - Here you can download ready-made translations of the config into your language (if it is translated)
# Ru - Здесь вы можете скачать готовые переводы конфига на ваш язык (если он переведён)
# Ua - Тут ви можете завантажити готові переклади конфігу на вашу мову (якщо вона перекладена)
# Ch(Simple) - 您可以在此处下载现成的配置翻译版本（如果已翻译）
# Fr - Ici, vous pouvez télécharger des traductions prêtes à l'emploi de la configuration dans votre langue (si elle est traduite)
# La - Hic potes download praeparata configurationis translationes in linguam tuam (si translatum est)
# De - Hier können Sie fertige Übersetzungen der Konfiguration in Ihre Sprache (falls verfügbar)
# https://github.com/Mirik9724/whitelist-ultra/blob/main/lang

# 全局占位符
# @nick - 玩家昵称（并非在所有地方都可用）
#
# 您可以在此处添加自定义占位符
placeholders:
  "@fu": "Fu!!!"
  "@custom": "自定义值"
  "@test": "测试！"

check_updates: "True"

error:
  file_: "测试信息"
  file_does_not-exist: "文件不存在。"
  underknewcom: "未知命令：@undsubcom"
  subc: "请指定子命令。"

commands:
  subc: "请输入子命令"
  usage: "用法：" # + 命令用法
  change:
    old_not_found: "未在列表中找到旧昵称。"
    duplicate: "新昵称已存在于列表中。"
    success: "昵称修改成功。"

  remove:
    m1: "玩家 @nick 已从白名单中移除。"
    m2: "玩家 @nick 不在白名单中。"
    kick: "您已被移出白名单。"

  add:
    m1: "玩家 @nick 已成功添加到白名单。"
    m2: "玩家 @nick 已经在白名单中。"

  check:
    found: "玩家 @nick 在白名单中。"
    not_found: "玩家 @nick 不在白名单中。"

  list: "白名单：" # + 白名单中的玩家列表
  player: "玩家 @nick"

reload: "插件已成功重新加载！"
kick: "您不在白名单中。"

version:
  v_no_connect: "无法获取插件的新版本。"
  v_no_found: "未发现更新。"
  v_found: "发现更新，最新版本为：@new_v"

# 使用 BStats 统计（请不要禁用，以便我了解插件的使用情况，匿名数据）
use-metric: True

# 仅用于开发者（me）：
debag: False # 当前未生效
# import net.Mirik9724.whitelist_ultra.Sp.WLU.nick
# WLU.nick
#
# plugin.logger.warning("")
# plugin.logger.info("")
# plugin.logger.fatal("")
# WLU.instance.logger.info("")
#
# println - 删除
