# En - Тут ви можете завантажити готові переклади of the config into your language (if it is translated)
# Ru - Здесь вы можете скачать готовые переводы конфига на ваш язык(если он переведён)
# Ua - Тут ви можете завантажити готові переклади конфігу на вашу мову (якщо вона перекладена)
# Ch(Simple) - 您可以在此处下载现成的配置翻译版本（如果已翻译）
# Fr - Ici, vous pouvez télécharger des traductions prêtes à l'emploi de la configuration dans votre langue (si elle est traduite)
# La - Hic potes download praeparata configurationis translationes in linguam tuam(si translatum est)
# De - Hier können Sie fertige Übersetzungen der Konfiguration in Ihre Sprache(falls verfügbar)
# https://github.com/Mirik9724/whitelist-ultra/blob/main/lang

# Глобальні плейсхолдери
# @nick - нікнейм гравця (можна використовувати не всюди)
#
# Тут ви можете додати власні плейсхолдери
placeholders:
  "@fu": "Fu!!!"
  "@custom": "Користувацьке значення"
  "@test": "Тест!"

check_updates: "True"

error:
  file_: "Тестове повідомлення"
  file_does_not-exist: "Файл не існує."
  underknewcom: "Невідома команда: @undsubcom"
  subc: "Будь ласка, вкажіть підкоманду."

commands:
  subc: "Будь ласка, вкажіть підкоманду"
  usage: "Використання: " # + використання команди

  change:
    old_not_found: "Старий нік не знайдено у списку."
    duplicate: "Новий нік уже є у списку."
    success: "Нік успішно змінено."

  remove:
    m1: "Гравця @nick видалено з білого списку."
    m2: "Гравця @nick немає у білому списку."
    kick: "Вас видалено з білого списку."

  add:
    m1: "Гравця @nick успішно додано до білого списку."
    m2: "Гравець @nick уже є у білому списку."

  check:
    found: "Гравець @nick є у білому списку."
    not_found: "Гравця @nick немає у білому списку."

  list: "Білий список: " # + список гравців у WLU
  player: "Гравець @nick"

reload: "Плагін успішно перезавантажено!"
kick: "Вас немає у білому списку."

version:
  v_no_connect: "Не вдалося отримати нову версію плагіна."
  v_no_found: "Оновлень не знайдено."
  v_found: "Знайдено оновлення. Остання версія: @new_v"

# Використовувати BStats-метрики
# (Будь ласка, не вимикайте, щоб я міг бачити статистику використання плагіна — анонімно)
use-metric: True

# Для розробника (me):
debag: False # наразі не працює
# import net.Mirik9724.whitelist_ultra.Sp.WLU.nick
# WLU.nick
#
# plugin.logger.warning("")
# plugin.logger.info("")
# plugin.logger.fatal("")
# WLU.instance.logger.info("")
#
# println - ВИДАЛИТИ