# Ru - Здесь вы можете скачать готовые переводы конфига на ваш язык (если он переведён)
# En - Here you can download ready-made translations of the config into your language (if it is translated)
# Ua - Тут ви можете завантажити готові переклади конфігу на вашу мову (якщо вона перекладена)
# Ch(Simple) - 您可以在此处下载现成的配置翻译版本（如果已翻译）
# Fr - Ici, vous pouvez télécharger des traductions prêtes à l'emploi de la configuration dans votre langue (si elle est traduite)
# La - Hic potes download praeparata configurationis translationes in linguam tuam (si translatum est)
# De - Hier können Sie fertige Übersetzungen der Konfiguration in Ihre Sprache (falls verfügbar)
# https://github.com/Mirik9724/whitelist-ultra/blob/main/lang

# Глобальные плейсхолдеры
# @nick - ник игрока (нельзя использовать везде)
#
# Здесь можно добавить свои плейсхолдеры
placeholders:
  "@fu": "Фу!!!"
  "@custom": "ПользовательскоеЗначение"
  "@test": "Тест!"

check_updates: "True"

error:
  file_: "Тестовое сообщение"
  file_does_not-exist: "Файл не существует."
  underknewcom: "Неизвестная команда: @undsubcom"
  subc: "Пожалуйста, укажите подкоманду."
commands:
  subc: "Пожалуйста, укажите подкоманду"
  usage: "Использование: " # +использование для команды
  change:
    old_not_found: "Старый ник не найден в списке."
    duplicate: "Новый ник уже есть в списке."
    success: "Ник успешно изменён."

  remove:
    m1: "Игрок @nick был удалён из белого списка."
    m2: "Игрок @nick не найден в белом списке."
    kick: "Вы были удалены из белого списка"

  add:
    m1: "Игрок @nick успешно добавлен в белый список."
    m2: "Игрок @nick уже в белом списке."

  check:
    found: "Игрок @nick есть в белом списке."
    not_found: "Игрок @nick нет в белом списке."

  list: "Белый список: " # + список игроков в WLU
  player: "Игрок @nick"
reload: "Плагин успешно перезагружен!"
kick: "Вы не в белом списке."

version:
  v_no_connect: "Не удалось получить новые версии плагина."
  v_no_found: "Обновление не найдено."
  v_found: "Обновление найдено, вот последняя версия: @new_v"

# Использование метрик BStats (Пожалуйста, не отключайте, чтобы у меня была информация о пользователях плагина (анонимно))
use-metric: True

# Для разработчика (меня):
debag: False # Сейчас не работает
# import net.Mirik9724.whitelist_ultra.Sp.WLU.nick
# WLU.nick
#
# plugin.logger.warning("")
# plugin.logger.info("")
# plugin.logger.fatal("")
# WLU.instance.logger.info("")
#
# println - УДАЛИТЬ
